version: "3.8"
services:
  dev-db:
    container_name: nest-bookmark-app
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - nestbookmark

networks:
  nestbookmark:
